166152322 Add support for drop sets
andela/wg-fortem pull request #27
Opened 2019-06-19 06:55 UTC by misocho

#### Title

Add support for drop sets
#### Description

Drop sets are essentially a technique where you perform an exercise and then drop (reduce) the weight and continue for more reps until you reach failure.

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) 

- [x] New feature (non-breaking change which adds functionality) 

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

- [ ] This change requires a documentation update

#### How Has This Been Tested?

#### Acceptance Criteria: 

#### Checklist:

#### PT stories

2019-06-19 13:18 UTC, martinMutuma approved these changes
Awesome work. Drop set feature works as expected
It would be better to pick up the absolute weights of percentages to ensure we stick to the defination of dropset

2019-06-19 13:20 UTC, justMuriithi requested changes
Superb job implementing drop sets. The ease with which I am getting my weight values is great. It would, however, be awesome if I as a user would be directed to know that changing repetitions in dropsets is optional.

2019-06-19 15:13 UTC, misocho commented
@justMuriithi, Thanks for the d=feedback. I've implemented it

2019-06-19 15:22 UTC, Tevinthuku approved these changes
Awesome work, this works as expected and also marking the reps fields as optional as requested by @justMuriithi. 
 It's convenient how I can just specify a percentage and an initial weight and have it calculate the exact weight I need to drop to in the next repetition

2019-06-19 19:25 UTC, justMuriithi approved these changes
Great job implementing the feedback.

2019-06-20 05:55 UTC, Kimaiyo077 approved these changes
Excellent work @misocho. The feature works as expected and thumbs up for implementing the feedback given.

2019-06-20 08:09 UTC, bencyn approved these changes
Great job. The drop sets feature works as expected. Indeed I've confirmed the page reloads
 after adding a drop set.

2019-06-20 10:18 UTC, michael-basweti approved these changes
Works as required

2019-06-20 10:19 UTC, merged