166152332-Add author field as a foreign key to Exercises
andela/wg-fortem pull request #4
Opened 2019-06-04 09:35 UTC by martinMutuma

#### Title
The author field should be a foreign key on exercises 
#### Description
This change is required so as to be able to get the author details for each exercise 

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) 

- [ ] New feature (non-breaking change which adds functionality) 

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

- [x] This change requires a documentation update

#### How Has This Been Tested?
- [x] End to end 
- [x] Unit tests

#### Checklist:
- [x] Code follows the agreed standards by the team
- [x] Code is Linted 
- [x] Add author field to exercises model as a foreign key
- [x] Add Assert statement for Author field in exercise tests

#### PT stories
[#166152332](https://www.pivotaltracker.com/story/show/166152332)

2019-06-04 11:04 UTC, misocho approved these changes
The author field on the exercises model is now a foreign key and it's great you have added a test for that.

2019-06-04 13:20 UTC, Kimaiyo077 approved these changes
Good work on making the field to be a foreign key and adding an assertion test for the changes.

2019-06-06 06:57 UTC, justMuriithi approved these changes
Great job adding a test for the addition of author field as a foreign key to exercises.

2019-06-06 07:02 UTC, michael-basweti requested changes

2019-06-06 07:02 UTC, michael-basweti commented on wger/exercises/models.py
> +    Author = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True,
I think us using `on_delete=models.DO_NOTHING` in our code will eventually create integrity issues in the case where we have deleted the user. We will be referencing to an object that doesn't exist.

2019-06-06 08:50 UTC, martinMutuma commented on wger/exercises/models.py
> +    Author = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True,
I have changed it to `model.SET_NULL`

2019-06-06 12:24 UTC, Tevinthuku approved these changes
Good job in making the author field a Foreign Key. We can now get more details from the author which is a good thing.

2019-06-06 19:48 UTC, michael-basweti approved these changes

2019-06-06 19:48 UTC, michael-basweti commented
This looks good

2019-06-06 19:48 UTC, merged